pr: none
trigger: none

jobs:
  - template: CI/job-doxygen.yml

  - job: Linux
    pool:
      vmImage: "ubuntu-latest"

    strategy:
      matrix:
        ubuntu1604:
          image: symless/synergy-core:ubuntu16.04
          packager: deb
          name: ubuntu16
          makeJobsLimit: 1
        ubuntu1804:
          image: symless/synergy-core:ubuntu18.04
          packager: deb
          name: ubuntu18
        ubuntu2004:
          image: symless/synergy-core:ubuntu20.04
          packager: deb
          name: ubuntu20
        ubuntu2104:
          image: symless/synergy-core:ubuntu21.04
          packager: deb
          name: ubuntu21
        ubuntu2204:
          image: symless/synergy-core:ubuntu22.04
          packager: deb
          name: ubuntu22
     

    container: $[ variables['image'] ]

    steps:
      - template: CI/checkout.yml
      - template: CI/Linux/linux-build.yml

  - job: MacOS
    strategy:
      matrix:
        catalina-std:
          image: macOS-10.15
          platform: x86-64
          version: 10.14
          buildType: "standard"
          prefix: "synergy"
        catalina-ent:
          image: macOS-10.15
          platform: x86-64
          version: 10.14
          buildType: "enterprise"
          prefix: "synergy-enterprise"
        catalina-business:
          image: macOS-10.15
          platform: x86-64
          version: 10.14
          buildType: "business"
          prefix: "synergy-business"
    pool:
      vmImage: $[ variables['image'] ]

    variables:
      QT_VERSION: "5.15.2"
      QT_PATH: "/usr/local/opt/qt"
      Qt5_DIR: "$(QT_PATH)/$(QT_VERSION)/clang_64"

    steps:
      - template: CI/checkout.yml
      - template: CI/MacOS/mac-build.yml

